config/routes.rb
Rails.application.routes.draw do

  get 'sitemaps/show'

  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  match '' => 'areas#show', :constraints => { :subdomain => true }, via: :get

  get 'home/index'

  root 'home#index'

  resources :escorts, only: [:show] do
    get :pictures
  end

  resources :areas, only: [:index, :show]

  get '/sitemap.xml.gz', to: 'sitemaps#show'
  

end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :escorts
end

app/models/escort.rb
class Escort < ActiveRecord::Base
  belongs_to :area

  serialize :interests
  serialize :pictures

  validates :name, presence: true
  validates :age, presence: true
  validates :pictures, presence: true

  def to_param
    "#{id} #{name}".parameterize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def areas
  	@areas = Area.all
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :areas
  
  def index
  end

  def show
  	@area = Area.find_by_name!(request.subdomain.humanize)
  	@areaTitle = @area.name
  	@escorts = Escort.all.where(area_id: @area.id)
  end
end

app/controllers/escorts_controller.rb
class EscortsController < ApplicationController
  before_action :areas

  def show
    @escort = Escort.find(params[:id])
    @areaTitle = Area.find(@escort.area_id).name
  end

  def pictures
  	@escort = Escort.find(params[:escort_id])
    @areaTitle = Area.find(@escort.area_id).name
  	@pictures = @escort.pictures
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :areas
  def index
  	@areaTitle = "UK"
  end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  def show
    redirect_to "http://dmlrnhuztcgz4.cloudfront.net/sitemaps/sitemap.xml.gz"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/escorts_helper.rb
module EscortsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/views/areas/index.html.erb
<h1>Areas#index</h1>
<p>Find me in app/views/areas/index.html.erb</p>

app/views/areas/show.html.erb
    <div class="contentmain">
      <div class="row skylinebg content">
        <h1 class="citytitle"><%= @area.name %> Escorts</h1>
        <div class="large-12 columns padding2v">
					<% @escorts.each_slice(3) do |row_escort| %>
					<div class="row padding3b">
						<% row_escort.each do |escort| %>
					    <div class="large-4 columns content1">
					    	<%= link_to escort_path(escort) do %>
						      <div class="large-3 columns singlelisting backgroundcover" style="background: url('<%= "http://escortdirectory-uk.com/" + escort.pictures.first %>');">
						      </div>
						      <div class="large-9 columns profileinfo singlelisting">
						        <div class="content1">
						          <h4 class="listingname"><%= escort.name %>, <%= escort.age %></h4>
						          <p class="font08"><%= escort.bio.truncate(100) %></p>
						        </div>
						        <p class="viewprofile text-center"><span class="font08">V</span>IEW PROFIL<span class="font08">E</span></p>
						      </div>
					      <% end %>
					    </div>
						<% end %>
					</div>
					<% end %>
        </div>
      </div>
      </div>

        <script type="text/javascript">
            (function() {

                /* matchHeight example */

                $(function() {


                  $(function() {
                    $('.singlelisting').matchHeight();
                  });


                });

            })();
        </script>

app/views/escorts/pictures.html.erb
    <div class="contentmain">
      <div class="row skylinebg content">
        <h1 class="citytitle"><%= @escort.name %></h1>
        <div class="row padding2v">
        	<div class="large-12 columns">
						<% @pictures.each do |picture| %>
							<img src="<%= "http://escortdirectory-uk.com/" + picture %>", alt="<%= @escort.name %>">
						<% end %>
        	</div>
        </div>
      </div>
    </div>



        <script type="text/javascript">
            (function() {

                /* matchHeight example */

                $(function() {


                  $(function() {
                    $('.listingpage').matchHeight();
                  });


                });

            })();
        </script>

app/views/escorts/show.html.erb
    <div class="contentmain">
      <div class="row skylinebg content">
        <h1 class="citytitle"><%= @escort.name %></h1>
        <div class="row padding2v">
        	<div class="large-3 columns listingpage">
        		<img class="escortpicture" src="<%= "http://escortdirectory-uk.com/" + @escort.pictures.first %>", alt="<%= @escort.name %>">
        	</div>
        	<div class="large-3 columns listingpage showbiobg">
    				<p class="margin0b padding05v content1 text-center generalinfo"><span class="escortprefix">AGE: </span><%= @escort.age %></p>
    				<p class="margin0b padding05v content1 text-center generalinfo"><span class="escortprefix">PHONE: </span><% if @escort.phone.blank? %> N/A <% else %><%= @escort.phone %></p> <% end %>
    				<p class="margin0b padding05v content1 text-center generalinfo"><span class="escortprefix">HEIGHT: </span><% if @escort.height.blank? %> N/A <% else %><%= @escort.height %></p> <% end %>
    				<p class="margin0b padding05v content1 text-center generalinfo"><span class="escortprefix">MEASUREMENTS: </span><% if @escort.measurements.blank? %> N/A <% else %><%= @escort.measurements %></p> <% end %>
        	</div>
        	<div class="large-6 columns padding1v content listingpage showbiobg padding1v">
        		<p class="font09"><%= @escort.bio %></p>

                <table style="width:50%">
                  <tr>
                    <td></td>
                    <td align="right">Incall</td> 
                    <td align="right">Outcall</td>
                  </tr>
                  <tr>
                    <td align="left"><%== @escort.firstPriceRow %></td>
                    <td align="left"><%== @escort.secondPriceRow %></td> 
                    <td align="left"><%== @escort.thirdPriceRow %></td>
                  </tr>
                </table>

        	</div>


        </div>
        <p class="text-center padding2v"><%= link_to escort_pictures_path(@escort), data: { no_turbolink: true } do %><span class="privategallerybutton"><span class="font12">V</span>iew <%= @escort.name %>'s Uncensored Private Galler<span class="font12">y</span></span><% end %></p>
      </div>
    </div>



        <script type="text/javascript">
            (function() {

                /* matchHeight example */

                $(function() {


                  $(function() {
                    $('.listingpage').matchHeight();
                  });


                });

            })();
        </script>

app/views/home/index.html.erb
    <div class="contentmain">
      <div class="row skylinebg">
        <div class="large-12 columns text-center padding6v">
          <h1 class="header1index">The UK's safest directory of independent escorts</h1>
          <div class="row">
            <div class="large-3 columns">
              <br>
            </div>
            <div class="large-6 columns">

                    <form METHOD="POST" onsubmit="window.open(this.elements[0].
                    options[this.elements[0].selectedIndex]. value,'_top'); return(false)">
                      <select class="margin0b locationselect" NAME="service" SIZE="1" width="30" onChange="window.open(this.options[this.selectedIndex].value,'_top')">
                      <option value="" SELECTED>Select your location</option>
                      <%= @areas.each do |area| %>
                        <option value="<%= root_url(:subdomain => area.name) %>"><%= area.name %></option>
                      <% end %>
                  </select>
                </form>
            </div>
            <div class="large-3 columns">
              <br>
            </div>
          </div>
        </div>
        <%= image_tag('skyline.png') %>
      </div>
      <div class="row">
        <div class="large-12 columns purplebg">
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @areaTitle %> Escorts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,600,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400italic,400,300italic,300' rel='stylesheet' type='text/css'>
</head>
<body>

	    <div class="row bg">
      <div class="row">
        <div class="large-12 medium-12 columns diagonalcontainer contentreset">
          <div class="diagonalhead">
          </div>
          <div class="row navbg">
            <div class="large-6 medium-6 columns logocontainer">
              <%= link_to root_url(:subdomain => false) do %><%= image_tag('logo.png') %><% end %>
            </div>
            <div class="large-2 medium-2 columns text-center padding18">
              <%= link_to root_url(:subdomain => false) do %><p class="margin0b navtext"><span class="fontswitch1">H</span>om<span class="fontswitch1">e</span></p><% end %>
            </div>
            <div class="large-2 medium-2 columns text-center padding18">
              <p class="margin0b navtext"><span class="fontswitch1">S</span>torie<span class="fontswitch1">S</span></p>
            </div>
            <div class="large-2 medium-2 columns text-center padding18">
              <p class="margin0b navtext"><span class="fontswitch1">V</span>ideo<span class="fontswitch1">s</span></p>
            </div>
          </div>
          <div class="row selectboxbg">
            <div class="large-4 medium-4 columns">
              <br>
            </div>
            <div class="large-4 medium-4 columns text-center">
                <form METHOD="POST" onsubmit="window.open(this.elements[0].
									options[this.elements[0].selectedIndex]. value,'_top'); return(false)">
									<select class="margin0b locationselect" NAME="service" SIZE="1" width="30" onChange="window.open(this.options[this.selectedIndex].value,'_top')">
									<option value="" SELECTED>Select your location</option>
                  <%= @areas.each do |area| %>
									   <option value="<%= root_url(:subdomain => area.name) %>"><%= area.name %></option>
                  <% end %>
									</select>
								</form>
            </div>
            <div class="large-4 medium-4 columns">
              <br>
            </div>
          </div>
        </div>
      </div>
    </div>


<%= yield %>
 

  </body>
</html>